= Ressources Utiles - Regex
Auteur: Corentin Chiodo
Date:: {docdate}
:doctype: book
:icons: font
:toc: left
:toc-title: Table des matières
:example-caption: 
:listing-caption: 
:source-highlighter: rouge

== Introduction

.Regex
****
Une expression régulière (ou "regex") est un ensemble de caractères qui forme un modèle de recherche. Ce modèle peut être utilisé pour rechercher, correspondre, extraire et manipuler des chaînes de caractères dans des textes. Les expressions régulières sont utilisées dans de nombreux langages de programmation, y compris Python, pour des tâches telles que la validation de formats, la recherche de motifs spécifiques dans des textes et la transformation de chaînes de caractères.

Voici quelques concepts clés des expressions régulières :

. Littéraux :
[disc]
* Ce sont des caractères qui correspondent exactement à eux-mêmes. Par exemple, l'expression régulière `abc` correspond à la chaîne de caractères "abc".

. Métacaractères :
[disc]
* Ce sont des caractères spéciaux ayant des significations particulières dans les expressions régulières. Par exemple :
+
====
 - `.` : correspond à n'importe quel caractère sauf un saut de ligne.
 - `*` : correspond à zéro ou plusieurs occurrences du caractère ou du groupe précédent.
 - `+` : correspond à une ou plusieurs occurrences du caractère ou du groupe précédent.
 - `?` : correspond à zéro ou une occurrence du caractère ou du groupe précédent.
 - `^` : correspond au début de la chaîne.
 - `$` : correspond à la fin de la chaîne.
 - `[]` : définit un ensemble de caractères, par exemple `[a-z]` correspond à n'importe quelle lettre minuscule de a à z.
 - `()` : groupe des caractères pour les utiliser ensemble dans une correspondance ou pour capturer des sous-chaînes.
====

. Échappement :
[disc]
* Pour utiliser les métacaractères comme des littéraux, on les précède d'un antislash `\`. Par exemple, pour rechercher un point réel, vous utiliseriez `\.` au lieu de `.`.

. Quantificateurs :
[disc]
* Ils spécifient combien de fois un élément peut être répété :
[square]
** `{n}` : exactement n occurrences.
** `{n,}` : au moins n occurrences.
** `{n,m}` : entre n et m occurrences.

****

== Renommer plusieurs fichiers selon une suite numérique sous Windows avec PowerRename 

.Via PowerRename
====

.Correspondre au nom complet du fichier :
[,console]
----
.*$
----
.Exemple d'un renommage 
[, console]
----
Dreamland T${padding=2start=11} <1>
----
<1> padding : 2 nombres. 
====

